services:
  ocserv:
    build: .
    container_name: ocserv
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    ports:
      - "4443:443/tcp"
      - "4443:443/udp"

    volumes:
      - ./ocserv:/etc/ocserv

  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray
    restart: unless-stopped

    ports:
      - "443:443/tcp"

    volumes:
      - ./xray/config.json:/etc/xray/config.json

    command: ["run", "-config", "/etc/xray/config.json"]
